### ISSUE TITLE
encounter a problem that the render results are not synchronize with the original video

### ISSUE THREAD

**Issue by visonpon** [ZhengyiLuo/UniversalHumanoidControl#10]
Hi @ZhengyiLuo ,I get my mocap data from rgb video and use trained model to test, but the render results seem dropped some frames and the motion cannot synchronize with the original video(usually move faster than the video). 
the motion pkl file has the same frames as video file, and are 30 fps,the rendered imitation and expert results are synchronize, but they all not synchronize with the video. it seems this caused by the mujoco render.
Hope you can help, thanks~

**Comment by ZhengyiLuo** [comment]
Ahh right. If you render the model through a visualizer, your rendering fps will be dictated by the viewer, whose fps can fluctuate based on your computer scheduling. To render with the same framerate as the simulation/data, checkout the [offscreen renderer](https://github.com/ZhengyiLuo/UniversalHumanoidControl/blob/095d78e265738369deaa619e606c1253eba68361/uhc/smpllib/smpl_mujoco.py#L284). You can also use this function on the viewer:

` self.env_vis.viewer.read_pixels(size[0], size[1], depth=False)[::-1, :, :],
                dtype=np.uint8,`

**Comment by visonpon** [comment]
I see, thank you~
