### ISSUE TITLE
imitation fails

### ISSUE THREAD

**Issue by interestingzhuo** [ZhengyiLuo/UniversalHumanoidControl#11]
When I try to imitate some noisy motion,  some frames will change suddenly. How can I fix it?

**Comment by interestingzhuo** [comment]
The case is "https://drive.google.com/file/d/1TTvQm24VOJsF0rzI-93IV_0-IYLJtL2v/view?usp=share_link"

**Comment by ZhengyiLuo** [comment]
There is a sudden big change in the reference motion (dark blue), where the person very suddenly turns by about 50 degrees. This would be impossible to imitate 100% accurately and is causing UHC to quickly snap to match the reference motion. 

 You can try to add some interpolation on the noisy motion or train a UHC model to better handle these large jumps. Hope that helps.
