### ISSUE TITLE
where to get the final results after mujoco simulation?

### ISSUE THREAD

**Issue by visonpon** [ZhengyiLuo/UniversalHumanoidControl#12]
Hi @ZhengyiLuo ,sorry to bother you again. 
I have got the pred results from trained model using
`eval_res = self.agent.eval_seq(take_key,loader`)
`pred_re = eval_res['pred']`

But it seems this results haven't went throuth physic simulation and the imitation motions are not so good as rendered results. 
So ,how to get the final results like above qpose format after physic simulation? 
Hope you can help, thank you~

**Comment by ZhengyiLuo** [comment]
Are you using the `eval_uhc.py` script? 

If you check the [copycat_visualizer](https://github.com/ZhengyiLuo/UniversalHumanoidControl/blob/master/uhc/utils/copycat_visualizer.py) script, you can see that `eval_res['pred']` is what the renderer is displaying, so I am not sure what could be wrong. Could you provide more information? The `eval_uhc.py` script also provides ways to dump and then load & visualize the dumped imitation results.

**Comment by visonpon** [comment]
Yes, I use the `eval_uhc.py`
I use `eval_res['pred'] `  and save it in bvh so that I can see the skeleton motion in blender. but in this way, the foot movements are not so good as the rendered results from mujoco.
So the problem must come from my conversion, my bad.

**Comment by visonpon** [comment]
@ZhengyiLuo, since I usually use bvh file , after get the joint euler from `eval_res['pred']` , I also need the original T-pose to do some retargeting so that the motion can trans to my bvh. do you have the T-pose file? thanks~
