### ISSUE TITLE
multiprocess error

### ISSUE THREAD

**Issue by interestingzhuo** [ZhengyiLuo/UniversalHumanoidControl#14]
test with ```full_eval = True``` raise "ConnectionResetError: [Errno 104] Connection reset by peer" by ```res = queue.get()``` in agent_copycat.py

**Comment by ZhengyiLuo** [comment]
The full_eval flag is used in training; are you referring to the testing during training procedure? 

Does code like 

```
python scripts/eval_uhc.py --cfg uhc_implicit_shape --epoch 4700 --data sample_data/amass_copycat_take5_test_small.pkl --mode stats
```

work on your end? It should be using the same underlying code. The multiprocessing code can indeed be tricky; it's working on my end so it could be the environment.

**Comment by interestingzhuo** [comment]
> The full_eval flag is used in training; are you referring to the testing during training procedure?
> 
> Does code like
> 
> ```
> python scripts/eval_uhc.py --cfg uhc_implicit_shape --epoch 4700 --data sample_data/amass_copycat_take5_test_small.pkl --mode stats
> ```
> 
> work on your end? It should be using the same underlying code. The multiprocessing code can indeed be tricky; it's working on my end so it could be the environment.

It seems that we cannot run multiprocess to get smpl mesh on cuda. Removing the smpl model works.

**Comment by ZhengyiLuo** [comment]
Yes. Cuda + multiprocess can be very tricky. Pytorch (cpu) + multiprocess  works from time to time with some tweaking.
