### ISSUE TITLE
is there as way to render virtual force  for implicit mode?

### ISSUE THREAD

**Issue by visonpon** [ZhengyiLuo/UniversalHumanoidControl#17]

**Comment by ZhengyiLuo** [comment]
Yes; probably just need to modify the rendering code to only render the root force.

**Comment by visonpon** [comment]
@ZhengyiLuo , sorry to bother your again.
In `humanoid_im.py` , the `set_action_spaces` method set `vf_dim=216`(24*9) for explicit, and in `copycat_visualizer.py` the `render_virtual_force` use a loop to render contact force for the 24 joints. but for implicit mode, the vf_dim=6, I have tried to render this value, but it seems not rights.
Hope you can help, thanks~
