### ISSUE TITLE
about the obs dim

### ISSUE THREAD

**Issue by yinkangning0124** [ZhengyiLuo/UniversalHumanoidControl#19]
Hi Zhengyi,
    I wonder is it possible to remove the shape and gender dimensions from the obs dim(that is 16+1), thus the obs dim turns to 640.
    Will this influence the model's performance?
Best,
Kangning

**Comment by ZhengyiLuo** [comment]
Yes you can remove them, but then you will need to train a new model for with a new config. 

Also if no shape and gender information is provided, training should also be done with the mean model instead of using the actual shape.
