### ISSUE TITLE
try to modify the xml file, but not work

### ISSUE THREAD

**Issue by visonpon** [ZhengyiLuo/UniversalHumanoidControl#20]
Hi @ZhengyiLuo , since in your project the T-pose is from smpl, but I want to use my own T-pose, so in order to avoid the retargeting problem, I  tried to modify the `humanoid_smpl_neutral_mesh.xml` by setting the joint's `pos` to different values based on my own T-pose, and set mujoco_model and vis_model's path in yml accordingly, but the render results make no difference. Hope you can give some advice, thank you~

**Comment by ZhengyiLuo** [comment]
In the current codebase, all the xml files are generated on-the-fly with [smpl_robot](https://github.com/ZhengyiLuo/UniversalHumanoidControl#smpl-robot) so modifying the neutral_mesh file will not have an effect. If you want to change the T-Pose then modification needs to make to the smpl_robot.
