### ISSUE TITLE
Constraint forces when computing desired accel

### ISSUE THREAD

**Issue by areiner222** [ZhengyiLuo/UniversalHumanoidControl#22]
Hi,

Thanks for your amazing work!

When [computing the desired acceleration](https://github.com/ZhengyiLuo/UniversalHumanoidControl/blob/790c556cd459c9be393afcf91a6316719f128dc8/uhc/envs/humanoid_im.py#L1014) in the humanoid environment, is there a specific reason you don't include the constraint forces (qfrc_constraint) ?

**Comment by areiner222** [comment]
I haven't gone through the stable PD controller yet and am by no means an expert, but from a first glance it looks like the the SPD controller assumes that the rigid body system equations of motion is expressed as:  
<img width="246" alt="Screen Shot 2023-06-28 at 4 16 52 PM" src="https://github.com/ZhengyiLuo/UniversalHumanoidControl/assets/15827111/1292ba76-f969-4284-a5d7-6fdd900d9ed5">

I believe the variable "C" in compute_desired_accel (i.e., the qfrc_bias term) includes the Coriolis, centrifugal, and gravitational forces (as explained in [mujoco documentation](https://mujoco.readthedocs.io/en/stable/computation.html) ). Also, from the SPD paper it seems that the C variable in the function encapsulates both C(q,q˙) AND the gravity component of τ_ext.

However, I think that the SPD papers τ_ext probably also includes the ground reaction forces and other contact forces? My understanding is that those forces in joint space can be found in the qfrc_constraint data from [mujoco](https://mujoco.readthedocs.io/en/stable/computation.html). Mujoco's forward dynamics equation is: 
<img width="186" alt="Screen Shot 2023-06-28 at 4 23 23 PM" src="https://github.com/ZhengyiLuo/UniversalHumanoidControl/assets/15827111/0f254596-b938-4cd1-ad8d-323951f66daf">
where (I think) qfrc_constraint = J_transpose x f

So I was wondering if desired acceleration output was computed in the absence of contact forces etc. and whether they should be included

**Comment by ZhengyiLuo** [comment]
Oh I see. The basic PD controller does not factor in the ground reaction forces (or any other external forces including gravity).  All the external forces are factored-in in the error terms. There are "gravity-compensated" PD controllers though. 

In SPD the gravity force is factored in when computing the acceleration for finite integration. You are right that C includes the Coriolis, centrifugal, and gravitational forces, but does not include the other contact forces. Most of the time in robotics we do not have access to the external contact forces (no additional sensors all over the robot's body); so (this is my understanding) external forces are not factored in here. I am sure there are specialized ones that do though.
