### ISSUE TITLE
smplh robot for isaac gym

### ISSUE THREAD

**Issue by interestingzhuo** [ZhengyiLuo/UniversalHumanoidControl#24]
I use the code to create the isaac gym robot for smplh. The R_Thumb3 is unnormal when use "capsule" and GAINS "R_Thumb3": [100, 10, 1, 150],
![smplh](https://github.com/ZhengyiLuo/UniversalHumanoidControl/assets/43921151/2cc6adda-15df-453e-996f-0210f9a5650b)

**Comment by interestingzhuo** [comment]
I fix the error by changing "L_Thumb3" in  the generated xml to 
```
<geom type="capsule" contype="1" conaffinity="1" density="1000" fromto="0.0053 -0.0009 0.0017 0.0212 -0.0037 0.0067" size="0.0083"/>
``` 
But I still do not find  the bug in the repo.

**Comment by interestingzhuo** [comment]
The node name of smplh is not compatible to the official smplh, such as chest, Spine. Could you provide a mapping between them ?

**Comment by ZhengyiLuo** [comment]
SMPLh capsule humanoid for Isaac is fixed in the latest push. 

As for the name, they have the same order as the official [SMPL ones](https://github.com/vchoutas/smplx/blob/main/smplx/joint_names.py), so mapping would just be one-to-one. 


<img width="853" alt="image" src="https://github.com/ZhengyiLuo/UniversalHumanoidControl/assets/13114740/2a5114aa-367a-474c-8dfd-8d37056a594c">

**Comment by nate-gillman** [comment]
Hi @interestingzhuo--

Would you please share some brief instructions for how you got that Isaac Gym robot visualized? When I try to visualize the test_good.xml file, my humanoid looks very different... which files are you using to visualize? 

Thanks!!
Nate

**Comment by interestingzhuo** [comment]
> Hi @interestingzhuo
> 
> Would you please share some brief instructions for how you got that Isaac Gym robot visualized? When I try to visualize the test_good.xml file, my humanoid looks very different... which files are you using to visualize?
> 
> Thanks!! Nate
change the setting to be
robot_cfg = {
        'model': "smplh",
        "mesh": False,
        "rel_joint_lm": False,
        "upright_start": False,
        "remove_toe": False,
        "real_weight": True,
        "real_weight_porpotion": True,
        "replace_feet": True, 
        "masterfoot": False,
        "big_ankle": True,
        "master_range": 50,
        "body_params": {},
        "joint_params": {},
        "geom_params": {},
        "actuator_params": {},
    }
