### ISSUE TITLE
Visualizing in Isaac Gym

### ISSUE THREAD

**Issue by nate-gillman** [ZhengyiLuo/UniversalHumanoidControl#26]
Howdy--

Thanks for all your work on this!!

I'm trying to get this to work in Isaac Gym, and my first goal is to visualize your agent embodying AMASS data inside the Isaac Gym simulated environment. 

When I uploaded your test_good.xml file and loaded it as an asset in Isaac Gym, and animated it through its range of motion, I got some weird behavior (see attached video, where I used the joint-monkey.py script that comes with the IsaacGym installation. This script reads in an asset file and moves the asset through all the ranges of motion afforded to them in their .xml construction: https://drive.google.com/file/d/1FCvmDjmMSqoeGs72bZ_-i_gfvVIP46aw/view?usp=sharing)

The behavior:
1. Lots of spacing between the joints (e.g. the arm isn't touching the torso, the femur isn't touching the pelvis)
2. Where the kneecap should be, it appears an ankle is, e.g. the agent's toes wiggle where the kneecap is, see the video

I wanted to ask if this behavior is expected, and if you have other tips for how to get this up and running on Isaac Gym... thanks for your help!!

Cheers
Nate

**Comment by ZhengyiLuo** [comment]
Did you use the `smpl_local_robot.py` for generating isaac humanoid?

**Comment by nate-gillman** [comment]
I didn't, I just used the `test_good.xml` file that's in the repo, and it loaded successfully so I assumed that wasn't the problem (it appears that file is output by the smpl_local_robot.py file). But if you think I should re-build that .xml file using the script, I can try that

**Comment by ZhengyiLuo** [comment]
Ahh, yeah `test_good.xml` probably is still pointing to the result from `smpl_robot.py`, which is the humanoid used for mujoco. You should run `smpl_local_robot.py` to create new xml files. In my code all of the xml files are generated on the fly so the existing one in the repo are mostly for debugging purposes.

**Comment by nate-gillman** [comment]
Got it, I rebuilt it from scratch and it worked this time. Thanks a lot for the help!!
