### ISSUE TITLE
Can UHC get the capsule SMPL-X robot for IsaacGym?

### ISSUE THREAD

**Issue by wyhuai** [ZhengyiLuo/UniversalHumanoidControl#27]
I tried to run smpl_local_robot.py with "mesh" as False, but it did not work.

**Comment by ZhengyiLuo** [comment]
What's your error message? Seems to be working on my end:

![Screenshot from 2023-08-29 16-05-32](https://github.com/ZhengyiLuo/UniversalHumanoidControl/assets/13114740/642b6ff4-8e08-4172-97b8-969d17d11175)

**Comment by wyhuai** [comment]
Traceback (most recent call last):
  File "uhc/smpllib/smpl_local_robot.py", line 2674, in <module>
    smpl_robot = Robot(robot_cfg)
  File "uhc/smpllib/smpl_local_robot.py", line 1358, in __init__
    self.load_from_skeleton()
  File "uhc/smpllib/smpl_local_robot.py", line 1538, in load_from_skeleton
    verts, joints, skin_weights, joint_names, joint_offsets, parents_dict, channels, joint_range = smpl_parser.get_offsets(
TypeError: get_offsets() got an unexpected keyword argument 'betas'

> What's your error message? Seems to be working on my end:
> 
> ![Screenshot from 2023-08-29 16-05-32](https://user-images.githubusercontent.com/13114740/264141364-642b6ff4-8e08-4172-97b8-969d17d11175.png)

**Comment by wyhuai** [comment]
Thanks, it solved! it is because I did not update some files you fixed...
