### ISSUE TITLE
hope can support data format that trans  from bvh to pkl

### ISSUE THREAD

**Issue by visonpon** [ZhengyiLuo/UniversalHumanoidControl#3]
Hi, @ZhengyiLuo ,thanks for sharing this wonderful work, I have add a pr to process the amass, hope it helps.

I also curious about whether bvh can trans to pkl, and I have read some discussion about this ,but the pose parameters in pkl are smpl format, so it comes to how to trans bvh's rotation vaule to  smpl pose.
hope you can give some advices~

**Comment by ZhengyiLuo** [comment]
For going from Bvh to pkl, you can checkout some open-source projects such as [this](https://github.com/KosukeFukazawa/smpl2bvh).
