### ISSUE TITLE
Can we train on different dataset?

### ISSUE THREAD

**Issue by Jatinkalal** [ZhengyiLuo/UniversalHumanoidControl#34]
Hey, amazing work by you..
Im still new to this field and exploring out, I had a doubt regarding
how to  use your model with other dataset like HumanML3D which is based on AMAAS.
Im trying to use generated motions from another generative model instead of input reference frames.

Thankyou.

**Comment by Jatinkalal** [comment]
Hi any updates on this issue ?
Thank you.

**Comment by ZhengyiLuo** [comment]
Hi! Please checkout [PHC](https://github.com/ZhengyiLuo/PHC) and [PHC_MJX](https://github.com/ZhengyiLuo/PHC_MJX/tree/master) for an updated version of the motion imitation task. If you want to use UHC, then please follow the [data processing step](https://github.com/ZhengyiLuo/UHC?tab=readme-ov-file#data-processing-for-training--evaluating-uhc).

**Comment by Jatinkalal** [comment]
Thanks for reply!
With using UHC for motion imitation specifically on 3D key points from MDM , how can I use pretrained model of UHC, is it to  edit accordingly in data_procesing_step  or should I need to train again?
