### ISSUE TITLE
Get amass data and smpl model

### ISSUE THREAD

**Issue by yinkangning0124** [ZhengyiLuo/UniversalHumanoidControl#4]
Hi Zhengyi,
    Thanks for your wonderful work and code release, I want to know how to get the training data and which smpl models to download and which folder to place them. Thanks!

**Comment by ZhengyiLuo** [comment]
Data processing scripts for AMASS has being added. 

For SMPL, you will need to have downloaded smpl model files from [SMPL](https://smpl.is.tue.mpg.de/), [SMPL-H](https://smpl.is.tue.mpg.de/downloads), and [SMPL-X](https://smpl-x.is.tue.mpg.de/downloads). Put them in the data/smpl folder.

**Comment by yinkangning0124** [comment]
Thanks for your reply!
