### ISSUE TITLE
size mismatch when running process_amass_db.py

### ISSUE THREAD

**Issue by yinkangning0124** [ZhengyiLuo/UniversalHumanoidControl#5]
Hi Zhengyi,
    When running process_amass_db.py, i am facing the problem of data size mismatch. I wonder how to fix this problem? I think i have convert the smplh model to the correct format.

![Screenshot from 2023-04-08 13-02-34](https://user-images.githubusercontent.com/45726315/230704282-bfc59254-8930-4195-acab-f529bd77fc54.png)

**Comment by yinkangning0124** [comment]
Don't worry, I have fixed this problem.

**Comment by Jatinkalal** [comment]
Hey can you tell me how did you fix this problem?
Thanks!.
