### ISSUE TITLE
Evaluation of motion imitation AMASS dataset.

### ISSUE THREAD

**Issue by interestingzhuo** [ZhengyiLuo/UniversalHumanoidControl#8]
How to reproduct the evaluation of motion imitation using target motion from the train and test split of the AMASS dataset in "From Universal Humanoid Control to Automatic Physically Valid Character Creation"

**Comment by ZhengyiLuo** [comment]
For evaluation, you can run 
`python scripts/eval_uhc.py --cfg uhc_implicit_shape --epoch 4700 --data sample_data/amass_copycat_take5_test_small.pkl --mode stats` on your processed data. The `--mode stats` runs evaluation on multiprocess mode. 

You will need the process AMASS train and test splits, following the [data processing instructions](https://github.com/ZhengyiLuo/UniversalHumanoidControl#data-processing-for-training--evaluating-uhc). 

Notice that in the aforementioned paper, some of the model used a "feet-only RFC", which is different from the trained weights.
