### ISSUE TITLE
Training speed 

### ISSUE THREAD

**Issue by interestingzhuo** [ZhengyiLuo/UniversalHumanoidControl#9]
The training is too slow, I use A100 and 192 cpu core, and set num_threads to 192. It still require 28 days for training. Do you have any trick to speed up the training?

**Comment by ZhengyiLuo** [comment]
The estimated time is misleading; I set the training episode to a very large number. Usually it converges within 5k epochs with RFC. Without RFC it takes a lonnnnnng time.

**Comment by ZhengyiLuo** [comment]
Also, usually I set num_threads to 30~50. I found that bigger than that usually isn't that really helpful.
